Update generated package.json for tests
This allows `yarn run tsc` for the generated test policy pack to succeed (to ensure it compiles). Otherwise, we get compiler errors like:

```
node_modules/@types/node/ts4.8/test.d.ts:881:34 - error TS1005: '?' expected.
```

due to `@types/node` using more recent TypeScript language features than TS 3.8.3.

We shouldn't be relying on the version of TypeScript from `@pulumi/pulumi` anyway. If we're using `tsc`, we should declare our own dev dependency on it.