Fix compile errors (#103)
* Fix compile errors

The `@pulumi/policy` library was updated to support remediations, but this repo hasn't been updated since then. This commit fixes some compile errors due to the changes there.

Note: This points out that we're missing a daily cron in this repro to catch these things sooner.

* Fix build/common.mk to match build location from pu/pu

* Update generated package.json for tests

This allows `yarn run tsc` for the generated test policy pack to succeed (to ensure it compiles). Otherwise, we get compiler errors like:

```
node_modules/@types/node/ts4.8/test.d.ts:881:34 - error TS1005: '?' expected.
```

due to `@types/node` using more recent TypeScript language features than TS 3.8.3.

We shouldn't be relying on the version of TypeScript from `@pulumi/pulumi` anyway. If we're using `tsc`, we should declare our own dev dependency on it.

* ci: Use a more recent version of Node.js

* Update getAmi call

Otherwise we get an error:

```
* Your query returned no results. Please change your search criteria and try again.
```